// layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import BottomNav from './components/BottomNav';
import SwipeMenu from './components/SwipeMenu'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Providers>
          <SwipeMenu />

          {/*  className="pt-24 pb-16 min-h-screen"背景色を指定せず、各ページ（children）の色が見えるようにする */}
          <main>
            {children}
          </main>

          <BottomNav />
        </Providers>
      </body>
    </html>
  );
}